# Generated by Django 5.1.2 on 2024-11-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='blog',
            name='coordinates1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='coordinates2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
