# Generated by Django 5.1.2 on 2024-11-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_img_blogimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='coordinates1',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='coordinates2',
            new_name='longitude',
        ),
    ]
